package com.example.app.flightprovidera.flightflifo;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.5
 * 2026-02-19T16:06:11.841+03:00
 * Generated source version: 4.1.5
 *
 */
@WebService(targetNamespace = "https://webservices.sabre.com/websvc", name = "OTA_AirFlifoPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OTAAirFlifoPortType {

    @WebMethod(operationName = "OTA_AirFlifoRQ", action = "OTA_AirFlifoLLSRQ")
    @WebResult(name = "OTA_AirFlifoRS", targetNamespace = "http://webservices.sabre.com/sabreXML/2011/10", partName = "body")
    public OTAAirFlifoRS otaAirFlifoRQ(

        @WebParam(partName = "header", mode = WebParam.Mode.INOUT, name = "MessageHeader", targetNamespace = "http://www.ebxml.org/namespaces/messageHeader", header = true)
        jakarta.xml.ws.Holder<MessageHeader> header,
        @WebParam(partName = "header2", mode = WebParam.Mode.INOUT, name = "Security", targetNamespace = "http://schemas.xmlsoap.org/ws/2002/12/secext", header = true)
        jakarta.xml.ws.Holder<Security2> header2,
        @WebParam(partName = "body", name = "OTA_AirFlifoRQ", targetNamespace = "http://webservices.sabre.com/sabreXML/2011/10")
        OTAAirFlifoRQ body
    );
}
