package com.example.app.flightprovidera.flightdetails;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 4.1.5
 * 2026-02-19T16:06:11.846+03:00
 * Generated source version: 4.1.5
 *
 */
@WebServiceClient(name = "OTA_AirFlifoService",
                  wsdlLocation = "classpath:/OTA_AirFlifoLLS2.1.1RQ.wsdl",
                  targetNamespace = "https://webservices.sabre.com/websvc")
public class OTAAirFlifoService extends jakarta.xml.ws.Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("https://webservices.sabre.com/websvc", "OTA_AirFlifoService");
    public static final QName OTAAirFlifoPortType = new QName("https://webservices.sabre.com/websvc", "OTA_AirFlifoPortType");
    static {
        URL url = OTAAirFlifoService.class.getClassLoader().getResource("/OTA_AirFlifoLLS2.1.1RQ.wsdl");
        if (url == null) {
            url = OTAAirFlifoService.class.getClassLoader().getResource("OTA_AirFlifoLLS2.1.1RQ.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(OTAAirFlifoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:/OTA_AirFlifoLLS2.1.1RQ.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OTAAirFlifoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OTAAirFlifoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OTAAirFlifoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OTAAirFlifoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OTAAirFlifoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OTAAirFlifoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns OTAAirFlifoPortType
     */
    @WebEndpoint(name = "OTA_AirFlifoPortType")
    public OTAAirFlifoPortType getOTAAirFlifoPortType() {
        return super.getPort(OTAAirFlifoPortType, OTAAirFlifoPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OTAAirFlifoPortType
     */
    @WebEndpoint(name = "OTA_AirFlifoPortType")
    public OTAAirFlifoPortType getOTAAirFlifoPortType(WebServiceFeature... features) {
        return super.getPort(OTAAirFlifoPortType, OTAAirFlifoPortType.class, features);
    }

}
