
package com.example.app.flightprovidera.flightdetails;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.1.5
 * 2026-02-19T16:06:11.803+03:00
 * Generated source version: 4.1.5
 *
 */
public final class OTAAirFlifoPortType_OTAAirFlifoPortType_Client {

    private static final QName SERVICE_NAME = new QName("https://webservices.sabre.com/websvc", "OTA_AirFlifoService");

    private OTAAirFlifoPortType_OTAAirFlifoPortType_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = OTAAirFlifoService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URI(args[0]).toURL();
                }
            } catch (URISyntaxException e) {
                e.printStackTrace();
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        OTAAirFlifoService ss = new OTAAirFlifoService(wsdlURL, SERVICE_NAME);
        OTAAirFlifoPortType port = ss.getOTAAirFlifoPortType();

        {
        System.out.println("Invoking otaAirFlifoRQ...");
        com.example.app.flightprovidera.flightdetails.MessageHeader _otaAirFlifoRQ_headerVal = null;
        jakarta.xml.ws.Holder<com.example.app.flightprovidera.flightdetails.MessageHeader> _otaAirFlifoRQ_header = new jakarta.xml.ws.Holder<com.example.app.flightprovidera.flightdetails.MessageHeader>(_otaAirFlifoRQ_headerVal);
        com.example.app.flightprovidera.flightdetails.Security2 _otaAirFlifoRQ_header2Val = null;
        jakarta.xml.ws.Holder<com.example.app.flightprovidera.flightdetails.Security2> _otaAirFlifoRQ_header2 = new jakarta.xml.ws.Holder<com.example.app.flightprovidera.flightdetails.Security2>(_otaAirFlifoRQ_header2Val);
        com.example.app.flightprovidera.flightdetails.OTAAirFlifoRQ _otaAirFlifoRQ_body = null;
        com.example.app.flightprovidera.flightdetails.OTAAirFlifoRS _otaAirFlifoRQ__return = port.otaAirFlifoRQ(_otaAirFlifoRQ_header, _otaAirFlifoRQ_header2, _otaAirFlifoRQ_body);
        System.out.println("otaAirFlifoRQ.result=" + _otaAirFlifoRQ__return);

        System.out.println("otaAirFlifoRQ._otaAirFlifoRQ_header=" + _otaAirFlifoRQ_header.value);
        System.out.println("otaAirFlifoRQ._otaAirFlifoRQ_header2=" + _otaAirFlifoRQ_header2.value);

        }

        System.exit(0);
    }

}
